namespace Pdb.CodeView;

public enum Leaf : ushort {
    LF_MODIFIER_16t = 0x0001,
    LF_POINTER_16t = 0x0002,
    LF_ARRAY_16t = 0x0003,
    LF_CLASS_16t = 0x0004,
    LF_STRUCTURE_16t = 0x0005,
    LF_UNION_16t = 0x0006,
    LF_ENUM_16t = 0x0007,
    LF_PROCEDURE_16t = 0x0008,
    LF_MFUNCTION_16t = 0x0009,
    LF_VTSHAPE = 0x000a,
    LF_COBOL1 = 0x000c,
    LF_LABEL = 0x000e,
    LF_NULL = 0x000f,
    LF_ENDPRECOMP = 0x0014,
    LF_REFSYM = 0x020c,
    LF_FRIENDCLS = 0x040b,   // (in field list) friend class
    LF_MODIFIER = 0x1001,
    LF_POINTER = 0x1002,
    LF_PROCEDURE = 0x1008,
    LF_MFUNCTION = 0x1009,
    LF_COBOL0 = 0x100a,
    LF_BARRAY = 0x100b,
    LF_VFTPATH = 0x100d,
    LF_OEM = 0x100f,
    LF_OEM2 = 0x1011,
    LF_SKIP = 0x1200,
    LF_ARGLIST = 0x1201,
    LF_FIELDLIST = 0x1203,
    LF_DERIVED = 0x1204,
    LF_BITFIELD = 0x1205,
    LF_METHODLIST = 0x1206,
    LF_DIMCONU = 0x1207,
    LF_DIMCONLU = 0x1208,
    LF_DIMVARU = 0x1209,
    LF_DIMVARLU = 0x120a,
    LF_BCLASS = 0x1400,      // (in field list) real (non-virtual) base class
    LF_VBCLASS = 0x1401,     // (in field list) direct virtual base class
    LF_IVBCLASS = 0x1402,    // (in field list) indirect virtual base class
    LF_INDEX = 0x1404,       // (in field list) index to another type record
    LF_VFUNCTAB = 0x1409,    // (in field list) virtual function table pointer
    LF_VFUNCOFF = 0x140c,    // (in field list) virtual function offset
    LF_ENUMERATE = 0x1502,   // (in field list) an enumerator value
    LF_ARRAY = 0x1503,
    LF_CLASS = 0x1504,
    LF_STRUCTURE = 0x1505,
    LF_UNION = 0x1506,
    LF_ENUM = 0x1507,
    LF_DIMARRAY = 0x1508,
    LF_PRECOMP = 0x1509,
    LF_ALIAS = 0x150a,
    LF_DEFARG = 0x150b,
    LF_FRIENDFCN = 0x150c,   // (in field list) friend function
    LF_MEMBER = 0x150d,      // (in field list) data member
    LF_STMEMBER = 0x150e,    // (in field list) static data member
    LF_METHOD = 0x150f,      // (in field list) method group (overloaded methods), not single method
    LF_NESTEDTYPE = 0x1510,  // (in field list) nested type definition
    LF_ONEMETHOD = 0x1511,   // (in field list) a single method
    LF_NESTEDTYPEEX = 0x1512,// (in field list) nested type extended definition
    LF_MANAGED = 0x1514,
    LF_TYPESERVER2 = 0x1515,
    LF_INTERFACE = 0x1519,
    LF_VFTABLE = 0x151d,

    // --- end of types ---

    // 0x1601..=0x1607 are only present in IPI stream, not TPI stream.

    LF_FUNC_ID = 0x1601,         // global func ID
    LF_MFUNC_ID = 0x1602,        // member func ID
    LF_BUILDINFO = 0x1603,       // build info: tool, version, command line, src/pdb file
    LF_SUBSTR_LIST = 0x1604,     // similar to LF_ARGLIST, for list of sub strings
    LF_STRING_ID = 0x1605,       // string ID

    // source and line on where an UDT is defined
    // only generated by compiler
    LF_UDT_SRC_LINE = 0x1606,

    // module, source and line on where an UDT is defined
    // only generated by linker
    LF_UDT_MOD_SRC_LINE = 0x1607,

    // The following four kinds were added to the wrong place in this enumeration.
    // They should have been added befor LF_TYPE_LAST.
    // But now it has been too late to change this :-(

    LF_CLASS2 = 0x1608,       // LF_CLASS with 32bit property field
    LF_STRUCTURE2 = 0x1609,   // LF_STRUCTURE with 32bit property field
    LF_UNION2 = 0x160a,       // LF_UNION with 32bit property field
    LF_INTERFACE2 = 0x160b,   // LF_INTERFACE with 32bit property field

    // These values are used for encoding numeric constants.
//    LF_NUMERIC = 0x8000,
    LF_CHAR = 0x8000,            // i8
    LF_SHORT = 0x8001,           // i16
    LF_USHORT = 0x8002,          // u16
    LF_LONG = 0x8003,            // i32
    LF_ULONG = 0x8004,           // u32
    LF_REAL32 = 0x8005,          // f32
    LF_REAL64 = 0x8006,          // f64
    LF_REAL80 = 0x8007,
    LF_REAL128 = 0x8008,
    LF_QUADWORD = 0x8009,        // i64
    LF_UQUADWORD = 0x800a,       // u64
    LF_REAL48 = 0x800b,
    LF_COMPLEX32 = 0x800c,
    LF_COMPLEX64 = 0x800d,
    LF_COMPLEX80 = 0x800e,
    LF_COMPLEX128 = 0x800f,
    LF_VARSTRING = 0x8010,       // string prefixed with u16 length
    LF_OCTWORD = 0x8017,         // i128
    LF_UOCTWORD = 0x8018,        // u128
    LF_DECIMAL = 0x8019,
    LF_DATE = 0x801a,            // 8 bytes
    LF_UTF8STRING = 0x801b,      // NUL-terminated UTF-8 string
    LF_REAL16 = 0x801c,
}

public static class LeafExtensions {
    public static bool IsImmediateNumeric(this Leaf leaf)
    {
        return (ushort)leaf < 0x8000u;
    }
}
